default_language_version:
    # force all unspecified python hooks to run python3
    python: python3.10
repos:
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    -   id: black

