version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/db.Dockerfile
    environment:
      # Note: ideally these should be passed via CI/CD build environment
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: example_root_password
    ports:
      - "3306:3306"
  etl:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/etl.Dockerfile
    depends_on:
      db:
        condition: service_started
    environment:
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      DB_HOST: db
    deploy:
      resources:
        reservations:
          cpus: '2'
  api:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/api.Dockerfile
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      DB_HOST: db
    depends_on:
      db:
        condition: service_started # healthcheck should also be included but we are ignoring it to limit the scope of this task
      etl:
        condition: service_completed_successfully
