version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/db.Dockerfile
    environment:
      # TODO: these should be passed via CI/CD build environment
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: example_root_password
  etl:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/etl.Dockerfile
    depends_on:
      db:
        condition: service_started
  api:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/api.Dockerfile
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    depends_on:
      db:
        condition: service_started # healthcheck should also be checked but we are ignoring it to limit the scope of this task
      etl:
        condition: service_completed_successfully
