version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/db.Dockerfile
    environment:
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: example_root_password
  etl:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/etl.Dockerfile
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: ./ops_utils/dockerfiles/api.Dockerfile
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: urparts
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    depends_on:
      - db
