version: '3'
services:
  db:
    build: ./ops_utils/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
  etl:
    build: ./ops_utils/etl.Dockerfile
    depends_on:
      - db
  api:
    build: ./ops_utils/api.Dockerfile
    depends_on:
      - db
